### ISSUE TITLE
Adding and deleting animations from sprites causes C3 to crash about 10% of the time

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1106]
## Problem description
After adding a new animation to a sprite, deleting other animations (especially with a lot of frames it seems, more than 100) crashes c#. This happens about 1 out of 10 deletes.

Using default theme.

## Attach a .c3p

Kiwi story

## Steps to reproduce

1. to any sprite add a few animations with a lot of frames 
2. do not close the panel
3. choose a different animation and delete it

## Observed result

C3 will crash about 10% of the time

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at l.ǃSIq (https://editor.construct.net/r72/main.js:63:203631) at l.ǃtA (https://editor.construct.net/r72/main.js:63:206400) at Function.ǃlIc (https://editor.construct.net/r72/main.js:73:384742) at ǃlIY.then (https://editor.construct.net/r72/main.js:73:373510) at 
Stack: Error: animation frame has no content at l.ǃSIq (https://editor.construct.net/r72/main.js:63:203631) at l.ǃtA (https://editor.construct.net/r72/main.js:63:206400) at Function.ǃlIc (https://editor.construct.net/r72/main.js:73:384742) at ǃlIY.then (https://editor.construct.net/r72/main.js:73:373510) at 
Construct 3 version: r72
URL: https://editor.construct.net/index.html
Date: Sun Dec 17 2017 20:32:04 GMT+0200 (GTB Standard Time)
Uptime: 20955.5 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r72
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by JeFawk** [comment]
I found a better way to reproduce this 100%. Sent Ashley an email since it contains a private project and I don't have time to strip it down right now.

**Comment by JeFawk** [comment]
![animationcrash](https://user-images.githubusercontent.com/7268697/34082609-327e8d62-e36a-11e7-922c-c0d7c899e57e.gif)

**Comment by AshleyScirra** [comment]
@DiegoScirra - "animation frame has no content" comes up in crash reports a lot, so this looks like an important one to fix. (I forwarded the email with the project to you.)

**Comment by DiegoScirra** [comment]
Fixed in r74.

**Comment by JeFawk** [comment]
It still happens in r75

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at i.ǃKkB (https://editor.construct.net/r75/main.js:63:208125) at i.ǃBa (https://editor.construct.net/r75/main.js:63:210896) at Function.ǃbkn (https://editor.construct.net/r75/main.js:74:369890) at ǃbky.then (https://editor.construct.net/r75/main.js:74:358658) at 
Stack: Error: animation frame has no content at i.ǃKkB (https://editor.construct.net/r75/main.js:63:208125) at i.ǃBa (https://editor.construct.net/r75/main.js:63:210896) at Function.ǃbkn (https://editor.construct.net/r75/main.js:74:369890) at ǃbky.then (https://editor.construct.net/r75/main.js:74:358658) at 
Construct 3 version: r75
URL: https://editor.construct.net/index.html
Date: Sat Jan 06 2018 14:00:26 GMT+0200 (GTB Standard Time)
Uptime: 1478.5 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r75
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment]
I was able to find some steps that sometimes throw the exception above and some other times throw an entirely new exceptions.

Something to do with undoing and redoing changes very quickly, as in keeping the undo shortcut pressed down. Looks like some nasty race condition caused by all the asynchronous code involved.

Anyway both should be fixed  in r77. But make sure to check it out.

**Comment by AshleyScirra** [comment]
r77 is out, please check again!

**Comment by DiegoScirra** [comment]
Haven't seen this one popup again in the crash reports, closing.
