### ISSUE TITLE
Cannot Shortcut Undo/Redo After Toggle Hide/Show Layer

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#15]
## Problem description

Cannot Shortcut Undo/Redo After Toggle Hide/Show Layer

## Steps to reproduce

1. Do some actions such as move a sprite object.
2. Click the toggle Hide/Show layout tick box on the Layers bar.
3. Undo.

## Observed result

Cannot undo when user just clicked on the layer visible toggle box.

After you used the layer visible toggle checkbox, you can do shortcuts like save but you **can't** do undo/redo shortcuts (with the keyboard).

The bug is that when the tick box is in focus, you can't do a shortcut undo/redo. Same goes to the animation properties -> tick boxes of Loop & Ping Pong.

Is not that you can't undo/redo them, is you can't undo/redo them when you just click on the tick box which makes the engine focus on it that cause the shortcut key to not function.

## Expected result

Should be able to undo/redo after clicking on the Layer's visible toggle tick box on the Layers bar.

## Affected browsers

* Chrome: yes

**Comment by jaydonteh** [comment]
Adding additional info:

The undo/redo doesn't work **only** with CTRL + Z / X. To check if all shortcut keys are also disable after toggling these tick boxes as stated above, found out Save shortcut (CTRL+S) still works. Which means specifically undo/redo shortcut keys are the ones with issue. This is because like the save shortcut key, the undo/redo shortcut key should be universally available when pressed. 

Perhaps it has something to do with these shortcut keys with the Sprite editor/(layout view & Event sheet).

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r17.

**Comment by jaydonteh** [comment]
Came back here to report that the issue is partially fixed.

In the Animation editor for Sprite objects, this is not fixed:
Animation properties -> tick boxes of Loop & Ping Pong.

**Comment by AshleyScirra** [comment]
@jaydonteh can you file a new issue for that?
