### ISSUE TITLE
R96 iOS missing Animation Properties

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1522]
## Problem description

*Enter a concise description of your problem here*
iOS animation Editor missing entire Animation Properties section on right
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open a project on the iPad
2. double click on a sprite
3. notice on the right side, there is no animation properties pain to include things like Speed, Loop, Ping Pong, Repeat To
4. Selected sprite properties does not include animation properties section either

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by zumwaltwood** [comment]
![468a4fb2-734e-4f36-b153-d3ac76610d27](https://user-images.githubusercontent.com/4122283/39217238-b06c7df4-47e4-11e8-9c8b-323506f60671.png)

**Comment by zumwaltwood** [comment]
![04f4f26f-c846-40be-adef-8dedcf42d89c](https://user-images.githubusercontent.com/4122283/39217276-e03a63fc-47e4-11e8-858c-d0be50306941.png)

**Comment by AshleyScirra** [comment]
The issue only occurs when changing a mobile device to desktop UI mode. Not all features correctly switched to desktop mode (which is why the Animations Editor didn't show animation properties). Should be fixed in the next release.

**Comment by zumwaltwood** [comment]
This issue exists in both mobile UI mode and desktop UI mode on the iPad, I need this fixed!
How do I re-open a ticket, this issue is not fixed and it is a huge issue for tablet and mobile development, do I need to create a new ticket with the exact same instructions or do a video and post is on YouTube then link the public video with the known issue for mobile development and C3? This is even a problem now in R98

**Comment by zumwaltwood** [comment]
Please refrain from closing tickets until they are actually resolved, this is not fixed so please open the ticket and leave it open until it is resolved then mention the release it was resolved in, this is still a bug and closing tickets just to close them does you no good.

**Comment by zumwaltwood** [comment]
Found the real issue, the animation editor is hidden behind the regular properties window, see my latest bug submission and watch the video, so no, it’s not resolved yet.
