### ISSUE TITLE
No such module 'PersonalizedAdConsent' - XCode

### ISSUE THREAD

**Issue by Bootfit** [Scirra/Construct-3-bugs#1696]
## Problem description
When archiving project in XCode I get the error:

**Swift Compiler Error - No such module 'PersonalizedAdConsent' _UserConsent.swift_**

In the Plugins/UserConsent.swift file - the first line **import PersonalisedAdConsent** throws up the error.

## Attach a .c3p

[testproject.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2103222/testproject.c3p.zip)

## Steps to reproduce

1. export project for iOS/XCode
2. archive project in XCode
3. get the error

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.79
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36
C3 release: r105 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 570 mb (1.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Sorry, leak over from some work I'm doing. Should have it patched in a second.

**Comment by shortercode** [comment]
Okay should be resolved now, can you tell me if it's working?

**Comment by Bootfit** [comment]
Ok I restarted Construct /r105 and Xcode.

Exported iOS/Xcode and imported into Xcode.

I still get the error Swift Compiler Error - No such module 'PersonalizedAdConsent' UserConsent.swift on start up but when I do a clean it fixes it and disappears. So I can now archive etc again, but when I install the app on my phone the screen flashes white and freezes. Don’t know if this is a related issue, but read elsewhere someone else was having a similar problem - I’ll do some digging.

**Comment by shortercode** [comment]
I think that's probably just xcode caching the previous project, it can be a little slow to notice changes. I've just refactored the userconsent system in the plugin so that it doesn't require that library anymore, so we won't be seeing this error anymore.
