### ISSUE TITLE
Touch input in layout not working in Windows store build.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1760]
## Problem description

Navigating the layout with touch is not working in the windows store build. I guess this is because touch events are disabled by default in Edge. If you open Construct 3 in edge it will have the same behaviour unless you go to about:flags and enable touch events. 

A lot of people are using touch enabled devices, like Microsoft Surface products, so it would be good if this worked. 

## Attach a .c3p

Any built in template file will do.

## Steps to reproduce

1. Open any project in Windows Store version of C3.
2. Use touch input to navigate the layout
3. Does not work as expected. (should work like in chrome)

## Observed result

Not working as it does in chrome.

## Expected result

Should work as in chrome.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: yes

**Comment by AshleyScirra** [comment]
Do you mean the editor or the runtime?

**Comment by tunepunk** [comment]
The editor.

**Comment by AshleyScirra** [comment]
Think this should be fixed in the next release, let's check again when it's out.

**Comment by AshleyScirra** [comment]
r109 is now out, can you verify it's working better with that?

**Comment by tunepunk** [comment]
Still doesn't work.

Navigating. Scrolling panning using 2 finger input not possible. 1 finger works for manipulating objects and drawing selection rectangle.

**Comment by AshleyScirra** [comment]
Was 1 finger interaction something that wasn't working previously but now is, but 2 finger interaction still isn't working? Or was 1 finger interaction always working?

**Comment by tunepunk** [comment]
Previously 1 finger was scrolling the page. Could not be used for selection or manipulation. 2 fingers zoomed all browser content. So nearly there. (This is the default edge behaviour with 'use touch events' flag set to "always off")

the 109 fix, solves the 1 finger input, 2 finger input no longer zooms the entire page or webview, but still doesn't work. Not sure it's picking up the second finger now for the scroll/zoom 2 finger operations.

**Comment by AshleyScirra** [comment]
It actually works correctly with two-finger touches in development, but not in the production version. I guess the build system is mangling something somewhere, which will make this tough to get to the bottom of, especially since Edge's dev tools seem to fail to debug the code...

**Comment by AshleyScirra** [comment]
Alright, took ages to get to the bottom of this, but think I've got a fix in for the next release. Let's verify when it's out.

**Comment by tunepunk** [comment]
Great news. I'll test this out then.

**Comment by AshleyScirra** [comment]
r116 is out now, can you verify it works with that?

**Comment by tunepunk** [comment]
Seems to work fine here now. Nicely done! thanks!

**Comment by tunepunk** [comment]
By the way. This fix for edge broke the same touch for firefox. works pre r116

**Comment by tunepunk** [comment]
Should I open a new issue for this? Because the things that didn't work in edge now doesn't work in firefox after this fix. r115 firefox touch input in layout view is fine, r116 edge is fine but firefox broke.

**Comment by AshleyScirra** [comment]
Yes, please file a new issue.
