### ISSUE TITLE
Z-Order bar not showing objects.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1965]
## Problem description

Sometimes Z-order bar is not showing any objects. This seem to happen randomly. But happens quite often. Only solution to fix is to restart Construct and hope it's correct. Sometimes it works to undock the zorder bar from the side bar. I'm not sure if this has something to do with the fact that I mostly have Zorder bar docked on the right hand side.

## Attach a .c3p

N/A 

## Steps to reproduce

1. Dock the Zorder bar on the right hand side.
2. Restart construct
3. Create a new project
4. Add a couple of sprites
5. Check the docked Z-order bar if they show up.

## Observed result

Z-order bar is not showing any objects.

## Expected result

Should show list of objects.

## Affected browsers

* Chrome: yes

<img width="946" alt="screen shot 2018-08-29 at 10 55 32" src="https://user-images.githubusercontent.com/27011641/44777661-74944000-ab7b-11e8-8d42-6b70e779f663.png">

**Comment by tunepunk** [comment]
<img width="949" alt="screen shot 2018-08-29 at 11 07 56" src="https://user-images.githubusercontent.com/27011641/44777861-e8364d00-ab7b-11e8-9d69-47140d18ffab.png">

After undocking and completely closing the Zorder bar, then selecting view Zorder bar, it now shows objects.

**Comment by jgp1971** [comment]
Happens to me as well.

**Comment by DiegoScirra** [comment]
Figured a way to reproduce this

1) Create a project
2) Add some sprites
3) Make sure the Z-Order Bar is showing everything
4) Hide 'Layer 0'
5) Select 'Layer 0' in the Z-Order Bar
6) Click on any of the invisible but highlighted instances in the layout view

At this point the Z-order Bar becomes goes empty

**Comment by DiegoScirra** [comment]
Fixed in r115

**Comment by jaydonteh** [comment]
@DiegoScirra Unfortunately I still get the empty Z order bug 😢. Perhaps because I also used global layers.

**Comment by jaydonteh** [comment]
I'll comeback and make a new issue once i found the way to reproduce it. Currently, it just happen when I'm least expecting it.

**Comment by jgp1971** [comment]
This is still happening quite frequently.

**Comment by bilgekaan** [comment]
It's not fixed.

**Comment by AshleyScirra** [comment]
Please file a new issue following all the guidelines; it could well be a different issue.
