### ISSUE TITLE
[C3 runtime] Breakpoint disable events without notice

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#2010]
## Problem description

This is going to be a very hard bug to reproduce. It happened to my main project after switching to C3 runtime and playing around with the breakpoint feature. 

Out of the blue, some event triggers stop working when I trigger in debug preview but works if I'm on the CPU profiler tab or in normal preview.

Usually when C3 hits a breakpoint it shows, but now it just entirely ignores the event. Basic debugging methods such as adding a browser.alert() in the affected event also do not trigger.

These affected events are in my case just function calls. Calling seems to work but the "on function" does not. These events work properly only if breakpoint is disabled, such as inside the CPU profiler tab or in normal preview. This lead me to think the breakpoint is the culprit.

## Attach a .c3p

Due to me not comfortable releasing my main project file, I have tried to strip my main project to just the few particular affected events but it never works. Once I changed the orders or moved the events, the bug cannot be reproduced again.

## Steps to reproduce

This is an issue that's hard to debug because the debugger itself is probably the issue. I really can't find a way to reproduce this and rightfully so, I shouldn't have to spend 4 hours pulling my hair on this.

## Observed result

When breakpoint is disabled, events triggers properly but gets whacky disabling events when breakpoint is enabled, ie. during debug preview.

## Expected result
Work as intended, with or without breakpoint feature running in the background.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.81
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 356 mb (4.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Could be another case of #2001 (fixed for next release), where some events do not run in debug mode.

**Comment by AshleyScirra** [comment]
r116 is out now, can you verify if it works with that?

**Comment by jaydonteh** [comment]
No, unfortunately the events that didn't fire before remains inactive in debug mode. But they will work if it's in the CPU profiler tab.

**Comment by AshleyScirra** [comment]
Without a project to test this on there's very little we can do. The debugger is still very new (it's only been out about a week) so it may well be reported with a smaller/simpler project and get fixed anyway. Alternatively if you can find a way to reproduce it in a new project please file it again.

**Comment by AshleyScirra** [comment]
FYI I found another case in the engine that was similar to the other bug we fixed, and corrected that for r117.2. Might be worth another test to see if that helped your case.

**Comment by jaydonteh** [comment]
Bug still remains. 

Also, this could be unrelated but anyway, after turning on Worker, not just events don't run, sometimes the game's canvas will go blank executing through an event. This is also not possible to reproduce and I'm stuck at keeping my projects away from Worker for now. I'll file another issue if I can reproduce them.

**Comment by AshleyScirra** [comment]
There's a bunch of issues with worker mode at the moment so we've moved it behind the experimental setting again for the time being. I wouldn't worry about worker mode issues until we re-enable it by default again.
