### ISSUE TITLE
Unable to save file in Windows 10 version

### ISSUE THREAD

**Issue by blueFireGames** [Scirra/Construct-3-bugs#2151]
## Problem description

Unable to save a file in a local folder when C3 obtained through the Windows 10 Store.  It does save a file with a .c3p extenstion but the file cannot be opened in C3 by double clicking on it.  The folder has is set to full permission for all users.

## Attach a .c3p

test.zip containing a test.c3p attached.

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/2476895/test.zip)

## Steps to reproduce

1.  Try to save an empty project after adding an empty "on frame start" event.

## Observed result

Error message that says "unable to save file."

## Expected result

The file to be saved in the selected location on the local hard drive.

## Affected browsers

NA

## System details

Error message attached:

![error](https://user-images.githubusercontent.com/8551252/46922576-0f849480-cfd9-11e8-97aa-cc3497902f33.png)

Platform information
Browser: Edge
Browser version: 17.17134
Browser engine: Edge
Browser architecture: 64-bit
Context: windows-store
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; MSAppHost/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
C3 release: r121 (beta)
Language setting: en-US 
Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable) 
Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Canvas toBlob is not supported. Image processing performance may be degraded.
Determining input device capabilities is not supported.
image-set() is not supported. Mouse cursors may appear with reduced quality.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Microsoft
Renderer: ANGLE (AMD Radeon HD 7640G Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:
WEBGL_compressed_texture_s3tc
OES_texture_float
OES_texture_float_linear
EXT_texture_filter_anisotropic
OES_standard_derivatives
ANGLE_instanced_arrays
OES_element_index_uint
WEBGL_debug_renderer_info
WEBGL_depth_texture
EXT_frag_depth
OES_texture_half_float
OES_texture_half_float_linear
WEBGL_lose_context
OES_vertex_array_object
WEBGL_draw_buffers
EXT_blend_minmax
EXT_shader_texture_lod
EXT_color_buffer_half_float
WEBGL_color_buffer_float
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:
Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)
Video information
Supported decode formats:
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)
<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
It looks like the project file actually saves successfully, it just reports an error at the end.

This looks like an exception thrown when updating recent projects because Edge does not support the insecure SHA-1 hash function ([ref](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest)). There is already existing code to produce widely-supported SHA-256 hashes in the editor, but for some reason this was duplicated elsewhere in the codebase with a different hash that doesn't work in Edge. I would change this, but it's not clear what the backwards compatibility implication is; assigning to @shortercode as it's his code.

**Comment by shortercode** [comment]
I find MS's decision to remove SHA-1 a little bewildering, as it has many safe non-cryptographic uses. This also causes backwards compatibility issues for applications in the process of upgrading... As far as I'm aware git is still using SHA-1 as it's primary content hashing algorithm, so any browser based git tool needs an external lib to support edge. But I do understand why they would want to discourage usage of it in new applications. 

Anyway, a plain switchover to SHA-256 would cause either loss of recent project data or duplicate entries. However, we can detect SHA-1 by checking the length of the hash. So this should allow us to upgrade to SHA-256 safely. It does mean we need to keep a SHA-1 hashing method for the time being, but it will only be used for the upgrade. I will also DRY the hashing utilities, I wasn't aware of the existing hashing methods when it was implemented.

**Comment by shortercode** [comment]
Should be resolved in the next release, upgrade path is existing recent project data.

**Comment by AshleyScirra** [comment]
Even with the fix, the development version is still showing me "Failed to open project" messages when opening existing projects from the cloud in Edge. It looks like it's still attempting to perform SHA-1 hashes in Edge which does not work.

We must not ever falsely show the error message; it makes it look like it's fundamentally broken and will send away users. I think clearing/losing all recent projects in just the Edge browser is an acceptable side-effect to resolve this. If necessary, I think clearing recent projects for everyone is also acceptable, providing it means we are exclusively using SHA-256 hashes with no codepath to attempt SHA-1 hashes. Further, you probably want to think about how to future-proof this so the hash can be changed easily again in future, in case it happens again to SHA-256.

**Comment by shortercode** [comment]
Sorry about that, there was an issue with how I'd implemented the upgrade. Fixed the problem and confirmed it's resolved on Edge.

I've also made an additional change so that failures to update the recent project list doesn't prevent files from saving/open. As this isn't the first issue that has been caused by recent projects, and given it's somewhat supplementary nature it shouldn't be causing such a damaging side effect.

**Comment by shortercode** [comment]
This should now be resolved in r123. Can you please confirm @blueFireGames

**Comment by blueFireGames** [comment]
I can confirm that this has been fixed on r123.2.  Thank you for fixing this.
