### ISSUE TITLE
C3 Runtime objects alignment changes after entering new monitor with different "Pixel Density"

### ISSUE THREAD

**Issue by DrathVader** [Scirra/Construct-3-bugs#2163]
## Problem description

This is a new issue related to [#2141] 

As of [R122] Alignment, object positioning as well hit area for Drag & Drop items are affected when browser is moved to a new monitor with a higher/lower "Pixel Density". Browser needs to be refreshed.

## Attach a .c3p

.c3p: https://1drv.ms/u/s!AnjqkTqN7Tavh-k7gKxidLVfXw_7gw

## Steps to reproduce

1. Drag window/browser from a "lower pixel density monitor" to a "higher pixel density monitor"

## Observed result

1. Fullscreen Scale: Off
2. Zoom, alignment, object positioning as well hit area for Drag & Drop items is affected. 

## Expected result

1. Everything should stay together. Alignment should not change from monitor to monitor.

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: Unknown
* Construct Preview: yes

## System details

1. No errors in console

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Presumably the devicePixelRatio changes when moving the window to a different density display. This is presumably a relatively rare hardware setup, and would be difficult to fix, since currently the engine assumes in many places that devicePixelRatio is constant. Given the high work to low impact issue this may take a while to solve.

**Comment by DrathVader** [comment]
Understandable, I will just prompt the user with a notification to save and reload when the pixel density and/or zoom level changes. This is an unfortunate bug In my case. Because the type of people who will use the app will most comonly use the desktop and web-app on multiple monitors.

**Comment by AshleyScirra** [comment]
You can already get the devicePixelRatio from the Browser object.

**Comment by AshleyScirra** [comment]
I had a quick look and there's only a couple of places where we cache devicePixelRatio, and updated them to re-read it every time, so it should respect changes. I haven't got a dual-monitor setup with differing devicePixelRatios though, so best to check the next release and see how it is there.

**Comment by DrathVader** [comment]
> You can already get the devicePixelRatio from the Browser object.

My apologies, I should have checked the documentation if it was an expression already. I got lazy with the auto fill hints when typing expressions since it did not suggest "Browser.DevicePixelRatio" Thank you for letting me know, I will now remember to always look in the documentation first. 

> Next Release

Sounds great, thank you for looking into this so quickly. Very much appreciated, the support you provide is outstanding.

**Comment by AshleyScirra** [comment]
r123 is now out, please check again!

**Comment by AshleyScirra** [comment]
Does your original project still demonstrate the issue? If not please provide a new one.

**Comment by AshleyScirra** [comment]
I found a couple more places devicePixelRatio was being cached, let's see if the next release is better again.

**Comment by AshleyScirra** [comment]
We just released r123.2. Can you check again there?

**Comment by DrathVader** [comment]
Still the same. 

Depending where you start before you drag the window to the new density monitor you also get different positioning of the text.

![v1](https://user-images.githubusercontent.com/4141075/47740850-0f6dd100-dc36-11e8-9879-2398f9b834ac.jpg)

![v2](https://user-images.githubusercontent.com/4141075/47740851-0f6dd100-dc36-11e8-8104-c6b1073d787c.jpg)

**Comment by AshleyScirra** [comment]
Have you tried putting something that constantly forces redrawing, e.g. a rotating sprite? If nothing changes in the game the runtime won't redraw the screen, and it might take a redraw to reflect the change.

**Comment by DrathVader** [comment]
Just added a rotating sprite and had the same issue. 

However, I do have good news. I set the "Canvas Size" on "Browser > On Resize" and the text held its correct position between the different monitor(s)

![working_example](https://user-images.githubusercontent.com/4141075/47757897-b9b11d00-dc65-11e8-9256-da2fe1863b24.jpg)

**Comment by NetOneGames** [comment]
So , I am not familiar with the original bug example project but running it and dragging the windowed preview from uwhd monitor to surface pro screen all the positions change and the text in the text boxes appears to scale all too big.

however I notice that you havent set a full screen scaling mode. or you have set it to OFF

if you set the full screen mode to say SCALE INNER 

then when you drag the windowed preview from one to another then everything is OK and stays the same scale and the same position.

one question Im asking is why  "Full Screen Scaling" mode is not just called "scaling mode" as it is also in effect when in windowed mode?

and my other question is if you dont set a "full screen" scaling mode should things stay in order when moving screen?

**Comment by DrathVader** [comment]
Correct, I have Fullscreen Scale set to [OFF] In my case this is required as I will be setting the canvas size dynamically.

**Comment by DrathVader** [comment]
Awesome! Thanks once again Ashley!

**Comment by AshleyScirra** [comment]
r126 is now out, please check again!

**Comment by AshleyScirra** [comment]
No reply for 2 weeks so closing.

**Comment by DrathVader** [comment]
> No reply for 2 weeks so closing.

Did not notice your reply in regards to r126. Looks like the positioning is now behaving correctly. 

However, I wouldn't just take my word for it. Since you mentioned you are using a single monitor, it may be good to pick up a 2nd or 3rd to check it out as well. Regardless, thank you very much for addressing this rather important bug.
