### ISSUE TITLE
Open recent project - folder icons are misleading

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2223]
## Problem description

Using open recent project, folder icons in front of names are looking random. Some subfolder ones have big icon while some main folder project has small icon. Some icons are even missing.

## Observed result
Folder icons should follow some patten to help users, atm it just look strange. 

Pic some projects have missing icon. I tried to replicate but couldn't
![openrecent](https://user-images.githubusercontent.com/28864889/47857020-463c1680-ddf1-11e8-9c9b-7dc14a829532.jpg)

## Expected result

Maybe just default icon for every project, medium size version of folder icon,  and you can click on folder icon to open that folder or on name that opens just the project.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 673 mb (4.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment]
Seems to be an issue with the menu system resizing the icons when the accompanying text is quite long. The icon is exactly the same, just a varying size. Probably need to limit the length of the text.

**Comment by AshleyScirra** [comment]
Maybe we just need a style to prevent flex shrinking on the icon?

**Comment by shortercode** [comment]
The icon seems reluctant to not shrink, but with the text wrapping modified it behaves itself. Do we think it should be truncated?

**With truncation**
![With truncation](https://user-images.githubusercontent.com/9051865/48215542-61230380-e37a-11e8-9f2a-f9aec15ae2dc.png)

**Without truncation**
![Without truncation](https://user-images.githubusercontent.com/9051865/48215547-64b68a80-e37a-11e8-8602-74d8bffe11fb.png)

**Comment by AshleyScirra** [comment]
Wrapping is better than truncation, let's go with that.

**Comment by shortercode** [comment]
Okay dokes, should be resolved in the next release.

**Comment by SnipG** [comment]
Release 130 has revert this fix!

**Comment by SnipG** [comment]
R145 - this still happens. No need to truncate it if it affect something else, just scroll the name if it's long one. 
![RecentSaves](https://user-images.githubusercontent.com/28864889/56138753-2c0d8380-5fa0-11e9-81bc-9e3c65871f85.jpg)

**Comment by AshleyScirra** [comment]
This issue was closed about 5 months ago, best file a new one.
