### ISSUE TITLE
[Desktop] Zoom Level Resets After Restarting C3 (Maximized Window Only)

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#2304]
## Problem description

Construct 3 seems to have issues with restoring information related to the display scale and window states. This is a very specific issue related to the maximized window state and display scale, resized windows don't seem to be affected.

## Steps to reproduce

1. Open C3 (r125) desktop and maximize the window
2. Inc/Decrease the display scale and restart C3
3. Notice that C3 didn't restore the window state (maximized)
4. Maximize the window again and restart C3
5. Notice that the window state is now correctly restored but the display scale isn't

## Observed result

Construct 3 seems to have an issue with restoring the maximized window state in combination with modified zoom levels.

## Expected result

Construct 3 should automatically restore the window state (maximized) and display scale levels after multiple restarts.

## Affected browsers

* NW.js: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8333333134651184
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r125 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 172 gb
Storage usage (approx): 72 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Tokinsom** [comment]
Worth noting that a few bars are set back to their default positions when the display scale is reset (project, properties, layers, tilemap, etc.). Also the actual program window is a little smaller than it should be (~8 pixels of my desktop are peaking through the bottom).

**Comment by shortercode** [comment]
Okay this should be resolved in the next beta, the display scale had been added on to the persistence system but didn't take into account that most of the restore process was skipped when the window was maximised. I've done a fairly hefty refactor of the system for the next release that fixes this as well as #2531

**Comment by TheRealDannyyy** [comment]
@shortercode The zoom level now stays but there is still an issue with the maximized window state not applying correctly.

## Steps to reproduce

1. Open C3 (r140) desktop and maximize the window
2. Inc/Decrease the display scale and restart C3
3. Notice that C3 didn't restore the window state (maximized)
