### ISSUE TITLE
Preview freezes randomly.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2398]
## Problem description

Preview freezes randomly. It seems like the events below cause the problem but I'm not sure. So I added a c3p file.

![image](https://user-images.githubusercontent.com/2965842/49460861-68b3bc00-f803-11e8-801e-069842972bb7.png)

## Attach a .c3p

[freezing-bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2645137/freezing-bug.zip)

## Steps to reproduce

1. Open the attached c3p and run preview
2. Press X a lot and shot the enemies.
3. Keep doing this until it freezes.

## Observed result

![2018-12-04_20-36-17](https://user-images.githubusercontent.com/2965842/49461268-50906c80-f804-11e8-8f1f-05b5e6983e3c.gif)

## Expected result

The game should keep working.

## First affected release

r128

## Affected browsers/platforms

* Chrome: yes
* Desktop: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r128 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 28 gb
Storage usage (approx): 256 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 755M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by TheRealDannyyy** [comment]
I could reproduce this as well. I think something is going wrong during the "collision check" of event 18, when used in combination with a wait action.

The issue doesn't seem to occur when toggling the wait action like this:
![wait crash](https://user-images.githubusercontent.com/15656049/49472980-18435b00-f811-11e8-9cf2-247c719146be.PNG)

**Comment by tunepunk** [comment]
I noticed a similar thing on my project... Minimizing the browser and reopening would resume the game again. Very odd.

**Comment by AshleyScirra** [comment]
Look in the browser console folks, it's crashing, not freezing. Anyway, turns out there's an edge case when using 'Wait' in an 'On collision' event - should be fixed for the next release.

**Comment by bilgekaan** [comment]
It's still happening in r131

![image](https://user-images.githubusercontent.com/2965842/49915534-365f2a00-fea7-11e8-8765-d7296d22c8b0.png)

**Comment by AshleyScirra** [comment]
Are you sure the repro project and steps are identical? I already identified the issue and fixed it.

**Comment by bilgekaan** [comment]
It's the same issue but maybe it wasn't about the collision.

- When I disable the spawn hitfx, it doesn't crash.
![image](https://user-images.githubusercontent.com/2965842/49970515-9f44b180-ff3c-11e8-811f-dd72c480cab0.png)

- When I disable set hitfx angle, it doesn't crash.
![image](https://user-images.githubusercontent.com/2965842/49970529-ab307380-ff3c-11e8-83c1-a33701859faf.png)

- When I disable hitfx any animation finished > destroy, it doesn't crash.
![image](https://user-images.githubusercontent.com/2965842/49970534-b2f01800-ff3c-11e8-8466-b9c80d872ef4.png)

- Also when I put more spawn hitfx actions, it crashes easier.
![image](https://user-images.githubusercontent.com/2965842/49970601-f21e6900-ff3c-11e8-94a9-db6ccd7bd5e8.png)

It's a weird bug.

**Comment by AshleyScirra** [comment]
I guess it's a different issue, can you file a new issue with the project that reproduces it most easily?
