### ISSUE TITLE
Blocking cookies won't allow C3 web app on Chrome to start

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2618]
## Problem description

Blocking all cookies makes the following console errors appear:
![52797816-55cd2b80-307f-11e9-87cc-038ea1ac7ef0](https://user-images.githubusercontent.com/7268697/52800342-3ab0ea80-3084-11e9-8a1f-5e2cb6a31b57.png)

## Steps to reproduce

1. Block all cookies in Google Chrome
2. Go to construct.net
3.

## More details

**Affected browsers/platforms:** tested on Google Chrome

**First affected release:** r136

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
This should be resolved in todays release, it missed the release notes. Could you give it a try?

**Comment by JeFawk** [comment]
Still happening

![image](https://user-images.githubusercontent.com/7268697/53034495-ee96e900-347b-11e9-8081-e8ad8a83740c.png)

**Comment by shortercode** [comment]
Okay looks like the original issue isn't a problem any more, but there's other problems... I'm looking into it now, looks like localforage trips our error system when there isn't any accessible storage method.

**Comment by JeFawk** [comment]
Dare i link #2615 here ?

**Comment by shortercode** [comment]
@JeFawk probably related, I've created a batch of fixes for this issue some of which could be applied to the runtime.

The editor now runs but there some unfortunate limits which can't be sidestepped ( no browser save, no cloud save, can't install plugins, no layout persistence, can't change any major settings as they require a restart )

**Comment by shortercode** [comment]
I reviewed the runtime code for the localstorage addon and it already has protection in place for this. Doesn't crash and correctly triggers the on error condition when I tried it with the "Local storage: high score" demo. As @AshleyScirra said you'll have to submit a project that repeats your issue, otherwise there isn't anything we can do.

The fixes for the editor should now be in place, so we don't crash any more. But as I said before there's some features that cannot work with cookies disabled.
