### ISSUE TITLE
Light theme colours in dark theme

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2958]
## Problem description

Since the latest update a few colours from the light theme appeared in the dark theme and they look very weird.

Completely black icons example: https://imgur.com/P9wapnN

## Attach a .c3p

Not needed.

## Steps to reproduce

1. Just open a blank project.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
I expect this is related to the timing of the values being read from the theme, @AshleyScirra has reworked the loading system substantially in this release. Assigning to him to review.

**Comment by AshleyScirra** [comment]
It looks like the theme CSS was broken by the recent editor loading optimisations. I've done some work on this and it should be working again in the next release.

**Comment by BonzerKitten7** [comment]
Any chance of reopening this issue? The bug is still present.

**Comment by AshleyScirra** [comment]
It's working fine for me in r151, so as far as I can tell, it is fixed.

**Comment by BonzerKitten7** [comment]
I'm pretty sure this is not the old purple tone.
https://i.imgur.com/bO3qWFt.png
This green also seems to be out of place.
https://i.imgur.com/TnYyYqp.png

**Comment by BonzerKitten7** [comment]
This orange too.
https://i.imgur.com/h92ZpX8.png

**Comment by AshleyScirra** [comment]
It looks like a different kind of problem to the one reported here, so please file a new issue - before/after screenshots comparing the last working release would be useful too.
