### ISSUE TITLE
Exported C3 project not working when building with Cordova CLI after release 153

### ISSUE THREAD

**Issue by gberenst** [Scirra/Construct-3-bugs#3036]
## Problem description

We use Cordova CLI 9 to build Apk after exporting from C3, it always worked fine. Now after release 153 it builds but remains black screen on device when executing, and console logs a FILE_NOT_FOUND. Problem is only solved when reverting C3 back to r152. 

## Attach a .c3p
[Link to C3P](https://drive.google.com/open?id=1Momfsynq_kDigTobtv8ivjeG6LIiToOo)

## Steps to reproduce

1. Export project as Cordova
2. Build apk using Android 7 SDK and Cordova CLI 9
3. Install apk on any Android 5+ device

## Observed result

Black screen when opening apk. It remains there. If debugging with chrome console, it logs and error (file not found)

## Expected result

Execute app in device as usual

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by gberenst** [comment]
We tried many alternatives. Creating a new cordova project, cleaning previous project, reverting Cordova CLI version back to 8.1.2. Remove and adding Android platform on cordova project, but nothing worked, except getting back to C3 r152 and exporting and build, which works fine.

**Comment by shortercode** [comment]
I expect this is related to recent changes to improve case insensitivity in projects, I will review the project you sent.

**Comment by AshleyScirra** [comment]
@gberenst - one issue others have had is C3 now exports everything lowercase, but Windows uses a case-preserving file system. Pasting files which only differ by case over an existing files preserves the old name instead of using the new name, creating a case mismatch. Then since Android is case sensitive it fails to find the files.

The workaround is to first delete all the files, and then paste them back in. Does this resolve the problem for you?

**Comment by gberenst** [comment]
Hi guys. Thanks for your help, pretty clear. @ashley, to prevent that I
first created a new project in cordova CLI, exported the C3 project again
from r153 (no old files in cordova's project folder), cleared old cache,
data and app from andorid device, and built it again. Still file not found
error shows up. May I try soemthing else?

**Comment by AshleyScirra** [comment]
Can you provide the full text of any error messages that appear? It's important to identify what's going on.

**Comment by gberenst** [comment]
![image](https://user-images.githubusercontent.com/48917913/59439279-58d8ee00-8dcb-11e9-8a7c-c5985ca16b70.png)

**Comment by shortercode** [comment]
I've done a build and can confirm it's not working. I'm not familiar with the changes so might be easier for @AshleyScirra to look at this issue?

Devtools:
![a](https://user-images.githubusercontent.com/9051865/59440502-01e51000-8def-11e9-8e09-0cee561326df.png)

APK contents:
![b](https://user-images.githubusercontent.com/9051865/59440516-04e00080-8def-11e9-92f3-31ea8632839c.png)

**Comment by AshleyScirra** [comment]
Alright, I'll take a look - odd that you see a different message though

**Comment by AshleyScirra** [comment]
Looks like an issue with case-sensitivity - the XML plugin exports xmldom.js but adds a script tag referencing xmlDom.js (the original name). Lowercasing that fixes it. Should be working in the next build. Don't know why an error message appeared about supportcheck.js, that looks fine.

**Comment by gberenst** [comment]
Hi again @AshleyScirra, I decided to migrate to v157, but problem is still happening same way!!! and now cannot get back to 152 with all the new stuff I´ve added. I understood this wouldn´t happen after 153. What  do you suggest?

**Comment by AshleyScirra** [comment]
This issue was closed a month ago and I verified the report as written was working at that time. Please file a new issue starting again and following all the guidelines if you still have trouble.

**Comment by gberenst** [comment]
Thanks @AshleyScirra, I´ve tried everything and finally solved it by: deleting old files, pasting them again, deleting cache and data, then uninstalling aok from device, then making a cordova clean action, and then rebuild, and it woked fine, so will not open a new thread. Thanks for your great support!

**Comment by shortercode** [comment]
@gberenst the Android build chain does some tricks to prevent copying the entire APK over the device each time which can sometimes experience issues. When doing a new build I normally uninstall the app beforehand, just to be sure I get a clean install.

**Comment by AshleyScirra** [comment]
If you use a case-preserving OS like Windows then because some files have changed only by case, you will indeed need to delete and re-copy the files, since pasting files over existing ones that only differ by case will not change the name.

**Comment by gberenst** [comment]
Thanks ashley! I first tried out just that, according to you advice in the
original thread, as it is the failure cause, but it still failed, so think
it is also important to execute cordova clean at cli in windows in order to
also remove old references with case mismatch and other stuff.
