### ISSUE TITLE
Tiny annoyances working with longer script files

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3083]
Two minor annoyances when working with longer script files. In particular, when switching between script file and eventsheet.

NOTE: this still persists in the just released 156.2

1. If you switch from eventsheet to script file, everything displays just white until you click it
2. If you switch from eventsheet to script file, it is all the way scrolled up

Makes it really annoying if you have to switch back and forth a bunch and have to search the line you were just editing over and over.

## Attach a .c3p

[longscript.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3330587/longscript.c3p.zip)

## Steps to reproduce

1. Scroll down the script file
2. Switch to eventsheet, then back to script file

## Observed result

The script file is initially displayed in white instead of showing the contents, also it always starts at the very top.

## Expected result

To see the content at once and also to get back where I previously edited.

## More details

Sometimes the whitescreen thing doesn´t affect the entire script file, so the script is white until line XX and then starts showing.

**Affected browsers/platforms:** 
Tested Firefox and Chrome, happens in both.

I think ever since scripting was in.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r156 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 98 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I think this has been a minor issue with text editor instances for awhile. I'm not sure what caused this regression but I've fixed it for the next release. Thanks for the report.

**Comment by shortercode** [comment]
Actually will keep this open, so that it can be reviewed after the release.

**Comment by Wackytoaster** [comment]
Hmm, I only did a brief check but it seems to be still present in the stable release.

**Comment by shortercode** [comment]
The change is coming in the next beta, release was already frozen by the time this change was written.

**Comment by Wackytoaster** [comment]
I see, thx for the info

**Comment by AshleyScirra** [comment]
r158 is now out, please check again!

**Comment by Wackytoaster** [comment]
Checked and it works now.

If I could change another little thing though: The line that was last edited will, upon switching to the tab, always be the very last line at the bottom. That´s fine but I think it would be even better if the exact scroll position is remembered.

Either way, I´d consider it solved (but improveable)

**Comment by shortercode** [comment]
I think that's probably because we only remember the position of the caret. When you move away the scroll position resets to the top, then when we restore it does the bare minimum of scrolling required, hence the caret will be on the last visible line. Your right this can probably be improved, I'll look into it.

**Comment by shortercode** [comment]
Okay I've committed a patch that will restore the scroll position, instead of just ensuring the cursor is on screen. I also made a change to ensure that the caret is focused as well. Will be in the next beta release.
