### ISSUE TITLE
[r31] Load Image for Sprite/Tiled Background not working with project files

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#347]
## Problem description

In C2 I can just use Load Image from URL with a local file like "image.png" and it shows the image but in C3 its not loaded.

## Attach a .c3p

[BugLoadImage.zip](https://github.com/Scirra/Construct-3-bugs/files/1026105/BugLoadImage.zip)

## Steps to reproduce

1. Load Image from URL from local project file

## Observed result

no image appears

## Expected result

image should be shown - works in C2

## Affected browsers

* Chrome: yes
* Edge: yes

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r32.

**Comment by TheBl4ckSh33p** [comment]
Hi. Still happening in r32. New project works but existing r31 project goes big load image. Tried preview and nw.js export.

**Comment by TheBl4ckSh33p** [comment]
I love iOS autocorrect. 🙄Does not load image.

**Comment by AshleyScirra** [comment]
Seems to be working fine for me in r32. Please file a new report following all the guidelines if you still have trouble.

**Comment by TheBl4ckSh33p** [comment]
It seems it only happens in the old project. Can I upload the game project somewhere where not everyone can just download/copy it?

**Comment by TheBl4ckSh33p** [comment]
I removed half of the game project and it still the same issue so I uploaded it as new bug report.
