### ISSUE TITLE
iOS Layout position wrong after keyboard closed.

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-3-bugs#3508]
## Problem description

When I export my C3 app to my iOS (Iphone XR) leaving Viewport Fit as Auto and Fullscreen Mode as Letterbox Scale the positioning of my app begins fine until the keyboard is opened. This pushes the app upwards as expected but then when the keyboard closes, the layout does not return to normal, it only comes down so far leaving part of the layout out of view at the top. 

If you change the Viewport Fit to Cover, the issue is even worse, when the keyboard closes the layout doesn't return at all, just stays half way up the screen.

I have also tried the various full screen options, hidden status bar but to no avail.

## Attach a .c3p

[keyboard_issue_ios.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3908133/keyboard_issue_ios.c3p.zip)

## Steps to reproduce

1. Export the above example.
2. Run or install on iOS device
3. Click in the edit box and then close the keyboard.

## Observed result

The layout does not return to its correct position.

## Expected result

For the layout to return to normal.

## More details

Video showing issue on my iphone XR
[C3_keyboard_issue.mp4.zip](https://github.com/Scirra/Construct-3-bugs/files/3908141/C3_keyboard_issue.mp4.zip)

**Affected browsers/platforms: iOS (Iphone XR) - 13.1.2** 

**First affected release: Broken in R171.3 Stable**

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_1
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 207 mb (1.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by andygilbert29** [comment]
Thought my luck was in when I noticed the latest beta has build option for iOS 13+, unfortunately no change at all. Problem still remains.

**Comment by shortercode** [comment]
I had a quick test on a iPhone 7, no issue. I'm guessing this is related to how we worked around the fullscreening issue on the notched iPhone's.

**Comment by AshleyScirra** [comment]
Just some wild speculation: Safari 13 now supports the Visual Viewport API; perhaps when the keyboard appears it resizes the visual viewport only and not the window, or some inconsistent mix of the two which leaves it with the wrong size.

**Comment by shortercode** [comment]
The viewport is actually the same size in my test. With the viewport parameter set to default the webview is pushed down by the height of the "unsafe" area at the top at the start, but after the resize the top on the webview is nearly 80px above the top of the screen. Leaving a sizeable gap at the bottom. The layout viewport does not trigger any resize events, but the visual viewport does.

**Comment by andygilbert29** [comment]
> The viewport is actually the same size in my test. But after closing the keyboard the top on the webview is nearly 80px above the top of the screen. Leaving a sizeable gap at the bottom. The layout viewport does not trigger any resize events, but the visual viewport does.
> 
> Interestingly setting viewport-fit:cover then reverting to viewport-fit:auto can correct the effect... But it's not exactly a clean solution. I'm going to do some additional testing, I can't help feel like there should be a nice solution to whatever evil Apple does to webviews on notched devices.

Hi I hope you manage to find clean fix soon but in the meantime just so I can continue with my project can you explain the temp fix you found above? Is this viewport toggle you refer too done in c3 or Xcode? Thanks

**Comment by shortercode** [comment]
The viewport hack was basically me modifying the `<meta type="viewport">` tag ( changing the viewport-fit value ) manually after the keyboard disappears using JS. I wouldn't recommend doing it, the viewport moves rather unpleasantly. Also detecting when the keyboard shows/hides is difficult.

We've come up with a better fix for this, I need to verify it doesn't behave unexpectedly when the device is rotated. But then it should be good to merge in for next weeks release.

**Comment by andygilbert29** [comment]
> The viewport hack was basically me modifying the `<meta type="viewport">` tag ( changing the viewport-fit value ) manually after the keyboard disappears using JS. I wouldn't recommend doing it, the viewport moves rather unpleasantly. Also detecting when the keyboard shows/hides is difficult.
> 
> We've come up with a better fix for this, I need to verify it doesn't behave unexpectedly when the device is rotated. But then it should be good to merge in for next weeks release.

Brill thank you, look forward to the fix. Have a client waiting to see app preview.

**Comment by shortercode** [comment]
Okay I've finished testing the fix and it seems to work correctly. It will be in next weeks beta, if you could check also that it resolves the problem for you that would be useful.

**Comment by andygilbert29** [comment]
Will do, thanks

**Comment by AshleyScirra** [comment]
r179 is now out, can you confirm if the issue is resolved there?

**Comment by AshleyScirra** [comment]
There's been no response for a week and the issue should be resolved, so closing.

**Comment by Sparsha1232** [comment]
> There's been no response for a week and the issue should be resolved, so closing.

Hi Ashley,
We are using iPhone X and the same issue still persists.. using r180
Just posted this on the forum-
https://www.construct.net/en/forum/construct-3/general-discussion-7/iphone-display-problems-using-149028#forumPost995685

Can you please reopen the case?
