### ISSUE TITLE
Failed to export project with minify

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4061]
## Problem description

Failed to export project with minify set to simple or advanced.

## Attach a .c3p

This happens with every c3p file, even a new blank one.

## Steps to reproduce

1. Export any project with minify set to simple or advanced.

## Observed result

Advanced returns an error - failed to export project
Simple - never finishing, need to force close.

## Expected result

Export should work.

## More details
I'm using the NWjs version, beta branch r208 with NWjs v0.46.4.0

**Affected browsers/platforms:** 

**First affected release:** 
Works on r204, broke on r206.
## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.46.4
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.46.4 (like Chrome/83.0.4103.116)
C3 release: r208 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 50 gb
Storage usage (approx): 48 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by layilpaht** [comment]
Use r208. It works (Although for me it is still not working but since my project is large hence that may be the issue.But it should work for you)

**Comment by avishaymizrav** [comment]
> Use r208. It works (Although for me it is still not working but since my project is large hence that may be the issue.But it should work for you)

Read my details, I'm already on r208, I only reported it because it was declared fixed and it's not for me.

**Comment by layilpaht** [comment]
Sorry !!! I just glanced at "first affected release" and I figured out that you were on r206

@AshleyScirra What exactly is happening with me:-
"no minification"= is running perfectly
"simple minification"= it just keeps on going and going. But if I open a tab/minimise chrome(it just works no idea why) then minification gets completed 
"advanced minification"= for empty projects and sample projects like space shooter,it works. But when I use advanced minification for my project,(the APK file is generated and installed on mobile) the project hangs on the loading bar and loading icon itself. And I am not even using any script in my game

**Comment by AshleyScirra** [comment]
It works in Chrome. It only affected advanced minify exports the NW.js build, because the minifier incorrectly detected the platform as node.js. It should be fixed in the next release. Simple minify worked OK for me.

**Comment by avishaymizrav** [comment]
The issue is still not resolved.
While I don't get the "failed to export" message on advanced, it is now getting stuck on the minify process, like in simple.
I gave it 10 minutes for a blank project, I think that's enough time to be certain it is not going to finish.
I tried downloading the latest NWjs, v0.47.1.0, but with that I don't even see the export dialog, just a bugged out blank window, this happens both on advanced and simple, but also on none, though it finishes the export, I don't see the progress window, just that blank bugged window.

Here's a little video, maybe it'll help...
[Screen capture on Youtube](https://www.youtube.com/watch?v=U-9VhPyUUsY)

**Comment by avishaymizrav** [comment]
@AshleyScirra I just noticed the window bug is not just for export, but for all process/progress windows, like loading a project, previewing and such.

**Comment by avishaymizrav** [comment]
@AshleyScirra Simple minify works, but advanced is till not working, I'm getting this error
![Capture2](https://user-images.githubusercontent.com/4296822/90417127-00cb0500-e0bc-11ea-9cc6-79dcbb5e7f41.PNG)

Any point of reporting it again?

**Comment by AshleyScirra** [comment]
It's reporting an error in the JS source code, most likely from a third-party addon. It appears to be unrelated to the issue originally reported in this thread. See: https://www.construct.net/en/forum/construct-3/plugin-sdk-10/third-party-addon-changes-153959

**Comment by avishaymizrav** [comment]
@AshleyScirra 

Man, you're sometimes too quick on the trigger to blame someone else, you should try being more helpful, I'm not against you, I'm on your team!
Maybe you should think first where you might have messed up or get a better QA guy,  I'm available for hire :)
I don't have any 3rd party plugins in my project.
But what you said in an unhelpful way actually helped, it gave me a direction and got me thinking, it's probably one of the official plugins.
So I started removing objects, tested and narrowed it down to the MoveTo behavior.
No events are needed, just add a sprite, add the behavior and try to export.
My bet is that it is because of something you changed for the timeline.

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines - they advise not to reply to closed bug reports. This is indeed an unrelated problem to the original report. We need reports to follow the guidelines otherwise normally it's impossible to help.
