### ISSUE TITLE
Z Order bar issues

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4172]
## Problem description
https://github.com/Scirra/Construct-3-bugs/issues/4150
The issue is still not fixed in r214, though it doesn't go all the way to the bottom, it's not placed where it should.
Z Order bar has issues with moving instances down the list + selection is lost if instances are selected from the layout.

## Attach a .c3p

https://github.com/Scirra/Construct-3-bugs/files/5121770/z-index-bug.zip

## Steps to reproduce

1. Select a few instances (works best with at least 4) from the top of the z order bar and try to drag them one or more slots down, they will jump one or two instance below where you drop them, , when dragging up it seems to work fine.

## Observed result

Ordering doesn't work right

## Expected result

Ordering to work right

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
I found another issue with the drag and drop logic when sorting instances, that should be fixed in the next beta.

I don't understand what you mean by **"selection is lost if instances are selected from the layout"** though. Normally the Z Order Bar should mimic the selection made in the layout and it should work the same the other way round too.

If you make a selection in the bar and then start a new selection in the layout, the selection in the bar will be lost, unless you where pressing **shift** while selecting in the layout, then the new instances will be added to the existing selection. If you do not press shift the click is counted as a completely new selection and the previous selected instances are no longer highlighted.

All of that seems to be working as expected.

**Comment by avishaymizrav** [comment]
The selection lost issue was fixed in the last beta.
Basically what happened was, I selected a few instances on the layout while holding shift (they also get selected in the z order bar), then if I tried to drag them (any one of the selected from the group) the selection got lost, and only the object I dragged got selected instead.

**Comment by DiegoScirra** [comment]
Ah ok, I thought it was still happening. I think all of this should be sorted in the next beta then.
