### ISSUE TITLE
Mesh Deform collision box not updated for Physics behavior after updating mesh points

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#4269]
## Problem description

Mesh Deform collision box not updated for Physics behavior after updating mesh points.

## Attach a .c3p

[MeshPhysicsCollBox.zip](https://github.com/Scirra/Construct-3-bugs/files/5342106/MeshPhysicsCollBox.zip)

## Steps to reproduce

1. Move top mesh points down beneath blue sprites w/ physics behavior
2.Blue sprites should fall further down, instead stay at original collision point / bbox
3.Using arrow keys, move red sprite w/ 8 dir behavior. It follows 'new' collision box.

## Observed result

Mesh point changing collision poly does not update physics collision behavior.

## Expected result

Mesh point changing collision poly should also update physics behavior.

## More details

Call an update to the physics behavior for collision box update?

**Comment by AshleyScirra** [comment]
Thanks, good catch - the physics behavior collision code wasn't updated with the mesh collision polygon changes. I've done this for the next release, so it should be working there.

**Comment by cragworks** [comment]
Still a problem.I tried adding mesh points to a physics behavior enabled sprite and having another sprite with physics fall onto it, but sometimes when I run the game, the collision is the bounding box instead of the mesh points. If I restart the game it works 75% of the time. Using the latest build and also beta build of Construct 3.

**Comment by AshleyScirra** [comment]
Please file a new issue following all the guidelines, as the issue covered here was fixed in October.
