### ISSUE TITLE
Bugs with hierarchy

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4296]
## Problem description

1. C3 crashes when trying to duplicate an object (with ctrl+c / ctrl+v) that has hierarchy attachments.
2. If you delete an object or instance the hierarchy (green arrow also) are not removed, if you save your project in this state and try to load it again, it will fail to load.
3. Duplicating a layout with hierarchy, C3 also crashes.

## Attach a .c3p

[hierarchybug.zip](https://github.com/Scirra/Construct-3-bugs/files/5397228/hierarchybug.zip)

## Steps to reproduce

Issue 1:
1. Select one of the objects in the layout or both.
2. Copy selection with ctrl+c
3. Paste selection with ctrl+v

Issue 2:
1. Delete the child objects.
2. Save project.
3. Try load project.

Issue 3:
1. Try duplicating the layout.

## Observed result

Issue 1:
C3 crash

Issue 2:
Error in opening file.

## Expected result

Duh

## More details

**Affected browsers/platforms:** NWjs 0.49.0

**First affected release:** r220-2

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: child does not have the correct parent
Stack: Error at Function.d.OTa (https://editor.construct.net/r220-2/main.js:286:41) at window.assert (https://editor.construct.net/r220-2/main.js:201:149) at d.$Yb.Zf (https://editor.construct.net/r220-2/projectResources.js:259:79) at d.$Yb.DNc (https://editor.construct.net/r220-2/projectResources.js:258:204) at n.Fa (https://editor.construct.net/r220-2/projectResources.js:243:366) at window.kl.ONb (https://editor.construct.net/r220-2/components/editors/layoutView/layoutView.js:74:450)
Construct 3 version: r220.2
URL: https://editor.construct.net/r220-2/
Date: Sun Oct 18 2020 11:34:04 GMT+0300 (Israel Daylight Time)
Uptime: 18.3 s

Platform information
Browser: NW.js
Browser version: 0.49.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.49.0-beta1 (like Chrome/86.0.4240.53)
C3 release: r220.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by avishaymizrav** [comment]
Issue #3, probably related, if you try to duplicate a layout with hierarchy, C3 also crashes.

**Comment by DiegoScirra** [comment]
The crash duplicating instances with hierarchy information has been fixed in the next beta.

**Comment by avishaymizrav** [comment]
> The crash duplicating instances with hierarchy information has been fixed in the next beta.

I can confirm it works, though duplicating the layout still crashes.

**Comment by DiegoScirra** [comment]
The second issue is now fixed, will show up in the next beta r222. Deleting an instance from a hierarchy should work as expected.

**Comment by DiegoScirra** [comment]
The third issue will be fixed in the next beta r222.
