### ISSUE TITLE
Crash on Preview Debug

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4368]
## Problem description

in Desktop version If debug preview then C3 crashed and closed without any crash report.
in Browser normal preview always shows loading screen.

## Attach a .c3p
Kiwi Story Template

## Steps to reproduce
1. Open Kiwi Story
2. Preview Debug mode - in Desktop Version
2. Normal Preview - Browser Version

## Observed result

Crash in Desktop Version
Infinite loading in browser

## Expected result
Debug preview 

## More details

**Affected browsers/platforms:** 
Chrome / Windows

**First affected release:** 
r226

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.49.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.49.0 (like Chrome/86.0.4240.75)
C3 release: r226 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 132 gb
Storage usage (approx): 102 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
There was an issue with the initial release as we had to make a server update. This should now be resolved - you'll need to clear your browser cache and then reload Construct, and it should be working again. Can you confirm this works?

**Comment by luckyrawatlucky** [comment]
@AshleyScirra browser works fine but Desktop version still crashing

**Comment by AshleyScirra** [comment]
It's working fine for me with NW.js 0.50. I assume it's just the server issue that we fixed.

**Comment by luckyrawatlucky** [comment]
My nw.js was 0.49 now I updated it and C3 is working fine now.
