### ISSUE TITLE
Previews and preview button breaks

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#5078]
On Windows/Chrome - The preview button will inconsistently break when previewing this project. I was unable to narrow down the exact situation when it does so, but it did happen eventually 100% of the time for me (reproduced over 30 times). Sometimes it happens on the first preview, sometimes on the second or third. I found that if the first preview is successful, the preview will continue to be successful as long as the preview window is not closed. However, if the preview window is closed and the preview button pressed again, even without making any changes, there is a chance for the preview to break. I was not able to reproduce this in new empty project at this time with the same system state (haven't tried rebooting Chrome or my system completely yet, in an attempt to narrow down the cause). Update: Issue persists after completely restarting Chrome.

There are a variety of error messages from Chrome I have encountered when it occurs in the preview window popup. Usually it is an "Aw, Snap! Something went wrong while displaying this webpage. Error code: STATUS_NOT_IMPLEMENTED".  If a preview attempted again, the error message from Chrome can become "Can't open this page. Try the following tips: Restart Chrome ect... Error code: STATUS_NOT_IMPLEMENTED". I have also seen "Aw, Snap! ... Error code: STATUS_ACCESS_VIOLATION". Update: I've encountered a new error code: STATUS_STACK_BUFFER_OVERRUN

If the preview button is pressed again after an error has occurred without closing the preview window, the preview window will try to refresh but fail again with an error message. Upon the third press and subsequently after that, the preview button becomes no longer responsive, and cannot be used in any form until Construct 3 is restarted.

If the preview window with error is closed before attempting to preview again, there is a chance for the next preview to recover and work normally. Although it eventually resulted in an error for me later.

https://www.dropbox.com/s/n2vodqcoznhuy9h/Bugreport_Advanced_Random_Permutation_Example.c3p?dl=0

## Steps to reproduce

1. Open Project
2. Press the preview shortcut button
3. Close the preview popup window
4. Repeat steps 2 and 3 until an error message is encountered. Usually occurs within 3 attempts for me. In the rare cases it didn't occur after 5 tries, sometimes I was able to induce it happening with a single click somewhere in the editor, such as highlighting a property or deselecting an object. Unfortunately this was also inconsistent, there wasn't a particular click/action I found to reliably cause the issue to occur, and it didn't always happen.
5. Upon a preview error occurring, attempt to preview a couple more times without closing the preview window.
6. The preview button will become unresponsive until Construct is restarted.

## Observed result

Preview window shows up with an error, and the preview button eventually stops working until Construct is reloaded.

## Expected result

No errors.

## More details

**Affected browsers/platforms:** Chrome/Windows10 

**First affected release:** Testing on latest stable R260, but I'm pretty sure this bug has been around since the beginning of Construct. I recall a forum post a long time ago describing this issue. Will try to find the post and update. Edit: https://www.construct.net/en/forum/construct-3/general-discussion-7/whats-favorite-c3-bug-cant-160473

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 93.0.4577.82
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
C3 release: r260 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 70 gb
Storage usage (approx): 155 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.22021.1002)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This report appears to describe the same issue as in #5008, which should have been fixed in r263, but also says it was only tested in r260. So I think this is something we already fixed. Please only file issues that reproduce in the latest beta to avoid reporting issues we've already fixed.

**Comment by oosyrag** [comment]
It still happens for me, same project, in R263 and R264. So far I've seen Chrome give me the three error codes mentioned above. Unable to determine any particular pattern of the error codes, although I feel like status_not_implemented shows up the most often.

I find the pattern of most interest is that closing the preview window before attempting to preview again will allow a chance of working or not on subsequent previews, but hitting the preview button without closing the preview window will break the button permanently (until C3 restarted).

**Comment by AshleyScirra** [comment]
Those are tab crashes so are Chrome issues, not Construct issues, and there's not much we can do about them. You could try reporting them to Google directly, but it will be important to have a reliable way to reproduce it.
