### ISSUE TITLE
Possible memory leak when pausing positioned audio

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5503]
## Problem description

When positioned audio is paused, some visuals start lagging and Chrome memory usage is constantly growing in Task Manager.

## Attach a .c3p

https://www.dropbox.com/s/adxuj4wycbhzh9r/AudioAtObjectBug.c3p?dl=0

## Steps to reproduce

Run the project.

## Observed result

Wait 5-20 seconds, you'll notice that the red sprite starts lagging behind mouse cursor.
Also, the memory usage for Chrome is constantly increasing when the project is left running, and it will eventually crash the browser.

## More details

I'm playing multiple sounds to make this problem more prominent. This also happens with one sound, but it takes longer time to notice.
Also, this happens much faster on higher frame rates (120-240).

**Affected browsers/platforms:** Seems to be happening only in Chrome/Edge.

## System details
<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 98.0.4758.102
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.3958333730697632
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
C3 release: r284.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 228 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
It looks like a bug in Chrome. I can reproduce in Chrome stable (v99), but it seems to work correctly in Chrome canary (v102). So I would guess this is a bug that Google already fixed. Does it work for you in Canary?

**Comment by dop2000** [comment]
I tried installing Chrome version 102.0.4967.0 on an old laptop, and unfortunately it doesn't look like the bug is fixed there.
If I leave the project running for a couple of minutes, its memory usage grows by ~1GB and the lagging of the red sprite becomes noticeable:
![image](https://user-images.githubusercontent.com/36763350/160275197-eb5ec670-c3e1-4e74-bb6a-40bd592d6bf2.png)

**Comment by AshleyScirra** [comment]
I can't reproduce this in Canary, and I suspect this is a Chrome issue anyway (when I could reproduce it, it seemed that Construct was doing everything right and Chrome was gradually slowing down in the Web Audio API). As I don't seem to be seeing the same thing as you, it's probably best if you file this directly with Google at crbug.com with detailed information about your setup.

**Comment by Interinactive** [comment]
Hi @AshleyScirra 

I've tried it on Canary on a gaming PC, my work PC and a laptop, the issue still occurs on all three of them.

I found that I had to leave it open for a few minutes to see the memory usage start to get eaten away. It hit around 1.5GB after 1 - 2 minutes.

**Comment by AshleyScirra** [comment]
This issue will need to be reported to Google at https://crbug.com. I don't believe it's related to Construct.

**Comment by Interinactive** [comment]
Is this description sufficient enough for a report on crbug?

https://github.com/Scirra/Construct-3-bugs/issues/5503#issuecomment-1080445746

Otherwise the only way I'd be able to explain the issue to them would be to clarify what I did in Construct, I'm unsure if they'd be willing to use C3 + the example file in their testing procedures.

**Comment by dop2000** [comment]
@AshleyScirra I agree with Interinactive - we know nothing about the API Construct uses, which methods are called to play/pause the audio, and we'll not be able to explain the issue in proper technical terms. Google support will probably redirect us to you again.

**Comment by AshleyScirra** [comment]
Normally I do file issues on behalf of users, but I'm not seeing the same thing as you, so I can't make the report - if they ask me questions or ask to check if it's fixed, I can't do that. So only an affected user can file the report and answer such questions.

I would advise to file an issue with Google and post the link here, and I will follow the issue and answer any technical questions about our engine.

**Comment by Interinactive** [comment]
> Normally I do file issues on behalf of users, but I'm not seeing the same thing as you, so I can't make the report

Just to confirm - you don't see the issue in Canary after leaving it open for up to 5 minutes? I have had it tested on 6 machines now (3 of my own) as well as my wife's laptop, another C3 developer and my friends PC, and it occurs 100% of the time on all of them.

**Comment by AshleyScirra** [comment]
I did not see any issue in Canary, but in Stable I saw a different issue: the CPU time of some Web Audio API calls seemed to get longer and longer over time, causing the FPS to drop. This seemed to be a different kind of problem, but even if it's related, there is nothing we can do about it: the problem is in Chrome.
