### ISSUE TITLE
Android export Deprecated BUG report

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#5800]
I get this error when exporting android signed :

Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK

Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$2@44ae26b2.
org.gradle.api.UncheckedIOException: Could not add entry '~~/settings.gradle' to cache fileHashes.bin (~~/fileHashes.bin).
at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:159)
at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache$2.run(DefaultMultiProcessSafePersistentIndexedCache.java:72)
at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:196)
at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:186)
at org.gradle.cache.internal.DefaultCacheAccess$UnitOfWorkFileAccess.writeFile(DefaultCacheAccess.java:411)
at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache.put(DefaultMultiProcessSafePersistentIndexedCache.java:70)
at org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$2.run(AsyncCacheAccessDecoratedCache.java:63)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.cache.internal.CacheAccessWorker$2.run(CacheAccessWorker.java:184)
at org.gradle.internal.Factories$1.create(Factories.java:25)
at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:222)
at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:203)
at org.gradle.cache.internal.CacheAccessWorker.flushOperations(CacheAccessWorker.java:174)
at org.gradle.cache.internal.CacheAccessWorker.run(CacheAccessWorker.java:144)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: No space left on device
at org.gradle.cache.internal.btree.FileBackedBlockStore.write(FileBackedBlockStore.java:118)
at org.gradle.cache.internal.btree.CachingBlockStore.flush(CachingBlockStore.java:60)
at org.gradle.cache.internal.btree.FreeListBlockStore.flush(FreeListBlockStore.java:92)
at org.gradle.cache.internal.btree.StateCheckBlockStore.flush(StateCheckBlockStore.java:76)
at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:157)
... 19 more
Caused by: java.io.IOException: No space left on device
at java.io.RandomAccessFile.writeBytes(Native Method)
at java.io.RandomAccessFile.write(RandomAccessFile.java:525)
at org.gradle.internal.io.RandomAccessFileOutputStream.write(RandomAccessFileOutputStream.java:46)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
at org.gradle.cache.internal.btree.ByteOutput.done(ByteOutput.java:62)
at org.gradle.cache.internal.btree.FileBackedBlockStore$BlockImpl.write(FileBackedBlockStore.java:200)
at org.gradle.cache.internal.btree.FileBackedBlockStore.write(FileBackedBlockStore.java:114)
... 23 more

FAILURE: Build failed with an exception.

* What went wrong:
Failed to create parent directory '~~/settings_5dj352aumzuebcv7hb8vrbrx7' when creating directory '~~/cp_settings4a0e9e6a4c349a78e523ba869bfbf889'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 0s

FAILURE: Build failed with an exception.

* What went wrong:
Could not update ~~/last-build.bin
> No space left on device

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 0s
Command failed with exit code 1: ~~/gradle -p ~~/android wrapper -b ~~/wrapper.gradle

**Comment by XIMIKATIK** [comment]
getting the same problem

**Comment by haiway85** [comment]
Having the same problem too. Host server down?

**Comment by haiway85** [comment]
hi~ any solution on this? tried just now but still can't.  Same with:

Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK

Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$2@63f9de08.
org.gradle.api.UncheckedIOException: Could not add entry '~~/settings.gradle' to cache fileHashes.bin (~~/fileHashes.bin).
at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:159)
at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache$2.run(DefaultMultiProcessSafePersistentIndexedCache.java:72)
at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:196)
at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:186)
at org.gradle.cache.internal.DefaultCacheAccess$UnitOfWorkFileAccess.writeFile(DefaultCacheAccess.java:411)
at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache.put(DefaultMultiProcessSafePersistentIndexedCache.java:70)
at org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$2.run(AsyncCacheAccessDecoratedCache.java:63)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.cache.internal.CacheAccessWorker$2.run(CacheAccessWorker.java:184)
at org.gradle.internal.Factories$1.create(Factories.java:25)
at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:222)
at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:203)
at org.gradle.cache.internal.CacheAccessWorker.flushOperations(CacheAccessWorker.java:174)
at org.gradle.cache.internal.CacheAccessWorker.run(CacheAccessWorker.java:144)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: No space left on device
at org.gradle.cache.internal.btree.FileBackedBlockStore.write(FileBackedBlockStore.java:118)
at org.gradle.cache.internal.btree.CachingBlockStore.flush(CachingBlockStore.java:60)
at org.gradle.cache.internal.btree.FreeListBlockStore.flush(FreeListBlockStore.java:92)
at org.gradle.cache.internal.btree.StateCheckBlockStore.flush(StateCheckBlockStore.java:76)
at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:157)
... 19 more
Caused by: java.io.IOException: No space left on device
at java.io.RandomAccessFile.writeBytes(Native Method)
at java.io.RandomAccessFile.write(RandomAccessFile.java:525)
at org.gradle.internal.io.RandomAccessFileOutputStream.write(RandomAccessFileOutputStream.java:46)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
at org.gradle.cache.internal.btree.ByteOutput.done(ByteOutput.java:62)
at org.gradle.cache.internal.btree.FileBackedBlockStore$BlockImpl.write(FileBackedBlockStore.java:200)
at org.gradle.cache.internal.btree.FileBackedBlockStore.write(FileBackedBlockStore.java:114)
... 23 more

FAILURE: Build failed with an exception.

* What went wrong:
Failed to create parent directory '~~/settings_3g3bwnmru2wxhxpvop9cbl2po' when creating directory '~~/cp_settings4a0e9e6a4c349a78e523ba869bfbf889'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 0s

FAILURE: Build failed with an exception.

* What went wrong:
Could not update ~~/last-build.bin
> No space left on device

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 0s
Command failed with exit code 1: ~~/gradle -p ~~/android wrapper -b ~~/wrapper.gradle

**Comment by AshleyScirra** [comment]
Apologies for the inconvenience, a problem with the build server caused it to run out of disk space. It should be working again now.

**Comment by haiway85** [comment]
Thanks so much @AshleyScirra , it's working now. Cheers~^^

**Comment by PaulGamerBoy101** [comment]
This problem is still occurring December 2024 (construct versions r416 - r420.2) And an Additional Error: "Failed to Create Keystore Log Below" Log: [Object Object] (I have tried to use my previously created keystores and that is when i get the original error.)
