### ISSUE TITLE
APK BUILD ERROR

### ISSUE THREAD

**Issue by Playtronic** [Scirra/Construct-3-bugs#6369]
## Problem description

Error building large APK

## Attach a .c3p

https://app.box.com/s/j02r1uo9o170caftq5788ve9hkbynd1b

## Steps to reproduce

1. Open the project
2. Export to APK
3. Observe the result

## Observed result

Build failed
Websocket is not closed / Cannot connect to build server

## Expected result

Successful build

## More details
The error occurred on 3 Windows devices and 2 Android devices, I also used 2 different connections. I have noticed that small projects compile successfully even though it takes a higher time than usual, large projects never compile correctly.

**First affected release:** 
R323

## System details

Platform information

Product: Construct 3 r323 (beta)
Browser: Firefox 108.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Language setting: pt-BR
Local storage

Storage quota (approx): 10 gb
Storage usage (approx): 12 mb (0.1%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon HD 5850 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
The build server had an outage. I've rebooted it and it should be working again now. Apologies for the inconvenience.

Remember that if it's urgent you can [also do offline builds with the Cordova CLI](https://www.construct.net/en/tutorials/building-mobile-apps-locally-21).

**Comment by Playtronic** [comment]
Restarting the server did not resolve the issue. The error remains exactly the same.
