### ISSUE TITLE
Sprite Editor: re-positioned origin not updating after changing sprite dimensions

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#784]
## Problem description

If you adjust the origin of a sprite in the sprite editor after changing the dimensions of the sprite the position of the origin is not updated when exiting the sprite editor - you have to reenter the editor and repeat the action.  This happens whether you use quick assign or manually adjust.

## Attach a .c3p

https://www.dropbox.com/s/puzf7fajwtqhjso/originBug00.c3p?dl=0

## Steps to reproduce

1. Open the attached project file
2. Select the sprite object and open in the sprite editor
3. Select Resize Image
4. Change the dimensions of the sprite to 256, 128, align-top left
5. Select the Origin button
6. Manually re-position the origin, or use quick assign to reassign it to the middle
7. Close the sprite editor

## Observed result

The origin has not been updated.  It will only update if you go back into the editor and reassign without making changes to the sprite's dimensions.

## Expected result

The new origin position should be shown upon closing the sprite editor.

Suggestion: quick assigning the origin should automatically respect subsequent sprite dimension changes; e.g. if I've already quick assigned to middle then if I change the dimensions the origin should move to the new centre position.

## Affected browsers

* Chrome: yes

## System details

</details>

**Comment by DiegoScirra** [comment]
Fixed in r56.

**Comment by jakemay74** [comment]
It looks like this is still occurring in r56 - I resize the sprite and adjust the origin in the sprite editor, but when I return to the layout window the old origin position is still showing.
