### ISSUE TITLE
MP3 audio breaks remote preview

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#835]
Related: issue #824 - original report did not follow guidelines, but managed to identify the issue via email.

Any project with an .mp3 audio file doesn't load in remote preview.

**Comment by AshleyScirra** [comment]
Have a fix on the way, needs a server-side change though.

**Comment by AshleyScirra** [comment]
Server was updated. Might need to clear browser cache to get the update but should be working now.

**Comment by Ind1eed** [comment]
Still doesn't work for me. Freezes randomly on 19%, 6% etc.
Also, i cleared my cache.

**Comment by Ind1eed** [comment]
Nevermind, works fine.
