### ISSUE TITLE
Glitch on flowcharts view

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#8499]
## Problem description
It happens when you close the project with a Flowchart view, when is open again the flowchart view starts in the top left view (not centered in the canvas where it was left before closing).
Also the likes connecting outputs and flowcharts are all moved to the top left corner of the blocks: 

![Image](https://github.com/user-attachments/assets/07705f67-e734-4784-a1d4-9507f679ef48)

Its not easy to reproduce, because it happens some times, i think something related with cache.

## Steps to reproduce

1. save the project while looking at a flowchart centered.
2. close the explorer and enter the project again
3. t

## Observed result
he project will show the left top corner position.

## Expected result
it shouls show the last position i was on the flowchart and the lines correctly drawn.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Can't reproduce this one. Something that sounds like this was fixed in r425, which was the first beta release after the last stable, so maybe it has already been fixed.

**Comment by kingpirux** [comment]
i was using stable, and now im using r431 and the issue persist.

**Comment by kingpirux** [comment]
ok ill close unitl im able to make a propper reproduce mode, but in the meantime i found a crash that could or not be related on r431.
