### ISSUE TITLE
Graphical glitches when using firefox (PC)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#937]
## Problem description

I'm seeing a lot af graphical glitches when using firefox on win 10. Current version is 56.0. The glitches look like its bart of the c3 ui, quickly flashing. Mostly in the top left corner.

## Attach a .c3p

N/A

## Steps to reproduce

1. Open C3 in firefox.
2. Open a random example project.
3. Click around and edit some events.

## Observed result

Graphical glitches appear on some/most UI interactions.

## Expected result

No glitches.

## Affected browsers

* Chrome: no
* Firefox: yes

**Comment by AshleyScirra** [comment]
There's a bug in r63 where the UI animations setting is enabled by default, but the setting is meant to be disabled in Firefox due to a Firefox bug that causes the glitches when using animations: https://bugzilla.mozilla.org/show_bug.cgi?id=1354501

It should be fixed for r64, but note when it comes out you'll need to clear the browser cache in Firefox to reset the setting.

**Comment by AshleyScirra** [comment]
Should be fixed now, please clear the cache in Firefox if you still have trouble.

**Comment by tunepunk** [comment]
I'm still having the same issues, even after clearing cashe, and completely uninstalling and reinstalling firefox. Any clue what it can be? File new bug? This needs still needs fix.

**Comment by AshleyScirra** [comment]
It looks fixed to me. If I open a new InPrivate window and open C3 it works fine (with UI animations disabled). I'd guess you haven't properly cleared the cache.
